version: "3.9"

services:
  # Catalog
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_PASSWORD=MySu]]erP@ss
      - POSTGRES_USER=appUser
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgressql/data/

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;Password=MySu]]erP@ss;User Id=appUser;Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Password=elie
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https.pfx
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/userSecrets:ro
      - ~/.aspnet/https:/https:ro

  # Basket
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_PASSWORD=MySu]]erP@ss
      - POSTGRES_USER=appUser
      - POSTGRES_DB=Basketdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgressql/data/

  #cache
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
  #API
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=Basketdb;Password=MySu]]erP@ss;User Id=appUser;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSetting__DiscountUrl=https://discount.grpc:8081
      - Kestrel__Endpoints__Https__Certificate__Password=elie
      - Kestrel__Endpoints__Https__Certificate__Path=/https/https.pfx
      - Kestrel__Certificates__Default__Password=elie
      - Kestrel__Certificates__Default__Path=/https/https.pfx
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/userSecrets:ro
      - ~/.aspnet/https:/https:ro
  #dicount
  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
      - ConnectionStrings__Database=Data Source=dicountdb.sqlite
      - Kestrel__Endpoints__Https__Certificate__Password=elie
      - Kestrel__Endpoints__Https__Certificate__Path=/https/https.pfx
      - Kestrel__Certificates__Default__Password=elie
      - Kestrel__Certificates__Default__Path=/https/https.pfx
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/userSecrets:ro
      - ~/.aspnet/https:/https:ro
