version: "3.9"

services:
  # Catalog
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_PASSWORD=MySu]]erP@ss
      - POSTGRES_USER=appUser
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgressql/data/

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;Password=MySu]]erP@ss;User Id=appUser;Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Password=elie
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/whttps.pfx
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/userSecrets:ro
      - /home/eliem/https:/https:ro

  # Basket
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_PASSWORD=MySu]]erP@ss
      - POSTGRES_USER=appUser
      - POSTGRES_DB=Basketdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgressql/data/

  #cache
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
  #API
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=Basketdb;Password=MySu]]erP@ss;User Id=appUser;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSetting__DiscountUrl=https://discount.grpc:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=elie
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/whttps.pfx
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6001:80"
      - "6061:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/userSecrets:ro
      - /home/eliem/https:/https:ro
  #dicount
  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Developmen
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Database=Data Source=/home/app/datadicountdb.sqlite
      - ASPNETCORE_Kestrel__Certificates__Default__Password=elie
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/whttps.pfx
    ports:
      - "6002:80"
      - "6062:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/userSecrets:ro
      - /home/eliem/https:/https:ro
  #Odering
  OrderDb:
    container_name: oprderDb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MySu]]erP@ss
    restart: always
    ports:
      - "1433:1433"

  #RabbitMq
  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
