version: "3.9"

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_PASSWORD=MySu]]erP@ss
      - POSTGRES_USER=appUser
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgressql/data/
